name: Install script

on:
  release:
    types: [created, published]

jobs:
  test:
    name: Install.sh
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install script
        run: ./cli/install.sh
