name: Test Installation

on:
  pull_request:

jobs:
  test-installation:
    name: Test Installation
    runs-on: macos-13
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run installation script
      run: cli/install.sh
