name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    name: Build ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - os: macos
            arch: arm64
            runner: macos-14
          - os: linux
            arch: x64
            runner: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install and build
        run: |
          pip install uv
          make install
          make bundle

      - name: Rename artifact
        run: |
          mv dist/rml.tar.gz dist/rml-${{ matrix.os }}-${{ matrix.arch }}.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rml-${{ matrix.os }}-${{ matrix.arch }}
          path: dist/rml-${{ matrix.os }}-${{ matrix.arch }}.tar.gz

  release:
    name: Publish Release
    needs: build  # Only runs if all build jobs succeed
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create version file
        run: |
          echo "${{ github.event.release.tag_name }}" > version.txt

      - name: Publish release with all assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/rml-macos-arm64/rml-macos-arm64.tar.gz
            artifacts/rml-linux-x64/rml-linux-x64.tar.gz
            version.txt
          draft: false  # Publishes the release
