name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - os: macos
            arch: x64
            runner: macos-latest
          - os: macos
            arch: arm64
            runner: macos-14
          - os: linux
            arch: x64
            runner: ubuntu-latest
          - os: linux
            arch: arm64
            runner: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install and build
        run: |
          if [ "${{ matrix.os }}" = "linux" ] && [ "${{ matrix.arch }}" = "arm64" ]; then
            docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace --platform linux/arm64 python:3.11 bash -c "pip install uv pyinstaller ruff && make bundle"
          else
            pip install uv
            make install
            make bundle
          fi

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/rml.tar.gz
