name: Build and Release

env:
  DARWIN_OS: darwin
  ARM64_ARCH: arm64
  LINUX_OS: linux
  X86_64_ARCH: x86_64

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    name: Build ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          # https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
          - os: ${{ env.DARWIN_OS }}
            arch: ${{ env.ARM64_ARCH }}
            runner: macos-15
          - os: ${{ env.DARWIN_OS }}
            arch: ${{ env.X86_64_ARCH }}
            runner: macos-13
          - os: ${{ env.LINUX_OS }}
            arch: ${{ env.ARM64_ARCH }}
            runner: ubuntu-24.04-arm
          - os: ${{ env.LINUX_OS }}
            arch: ${{ env.X86_64_ARCH }}
            runner: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install and build
        run: |
          pip install uv
          make install
          make bundle

      - name: Rename artifact
        run: |
          mv dist/rml.tar.gz dist/rml-${{ matrix.os }}-${{ matrix.arch }}.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rml-${{ matrix.os }}-${{ matrix.arch }}
          path: dist/rml-${{ matrix.os }}-${{ matrix.arch }}.tar.gz

  release:
    name: Publish Release
    needs: build  # Only runs if all build jobs succeed
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create version file
        run: |
          echo "${{ github.event.release.tag_name }}" > version.txt

      - name: Publish release with all assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/rml-${{ env.DARWIN_OS }}-${{ env.ARM64_ARCH }}/rml-${{ env.DARWIN_OS }}-${{ env.ARM64_ARCH }}.tar.gz
            artifacts/rml-${{ env.DARWIN_OS }}-${{ env.X86_64_ARCH }}/rml-${{ env.DARWIN_OS }}-${{ env.X86_64_ARCH }}.tar.gz
            artifacts/rml-${{ env.LINUX_OS }}-${{ env.ARM64_ARCH }}/rml-${{ env.LINUX_OS }}-${{ env.ARM64_ARCH }}.tar.gz
            artifacts/rml-${{ env.LINUX_OS }}-${{ env.X86_64_ARCH }}/rml-${{ env.LINUX_OS }}-${{ env.X86_64_ARCH }}.tar.gz
            version.txt
          draft: true # Keep the draft
