name: Unit Tests

env:
  RECURSE_INSTALL_URL: "https://install.recurse.ml"
  VERSION_CHECK_URL: "https://github.com/Recurse-ML/rml/releases/latest/download/version.txt"
  BACKEND_URL: "https://squash-322339097191.europe-west3.run.app"
  OAUTH_APP_CLIENT_ID: "Ov23liYqdgBWHJgs6HCd"
  RML_ENV_FILE: ".env.rml"
  RML_LOG_LEVEL: "DEBUG"


on:
  pull_request:

jobs:
  test:
    name: Unit Tests
    timeout-minutes: 5
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Set environment variables
        run: |
          echo "VIRTUAL_ENV=${{ github.workspace }}/env" >> $GITHUB_ENV
          echo "UV_PROJECT_ENVIRONMENT=${{ github.workspace }}/env" >> $GITHUB_ENV
      - name: Check out repository
        uses: actions/checkout@v4
  
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.16"
          enable-cache: true

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'

      - name: Install dependencies
        run: make install-test

      - name: Set up path
        run: |
          . $VIRTUAL_ENV/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV

      - name: Run unit tests
        run: make unit-test
