name: Unit Tests

on:
  pull_request:

jobs:
  test:
    name: Unit Tests
    timeout-minutes: 5
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Set environment variables
        run: |
          echo "VIRTUAL_ENV=${{ github.workspace }}/env" >> $GITHUB_ENV
          echo "UV_PROJECT_ENVIRONMENT=${{ github.workspace }}/env" >> $GITHUB_ENV
      - name: Check out repository
        uses: actions/checkout@v4
  
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.16"
          enable-cache: true

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'

      - name: Install dependencies
        run: make install-test

      - name: Run unit tests
        run: make unit-test
